### ISSUE TITLE
Company Communicator - Incoherent analytics data

### ISSUE THREAD

**Issue by l3noir** [cristianoag/microsoft-teams-apps-company-communicator#65]
Dear developers,

after sending a message through the Teams Company Communicator, analytics show incoherent data.

As shown in the screenshot below, for example, we have a message sent to over 2 thousands users but it appears that only 46 read it. It seems strange that such a small number of people actually read the message.
Furthermore, it is reported that over 200 users clicked on the call to action within the message. How can it be that a user that clicked the button doesn't appear to have read the same message?

Can you confirm on what circumstances a Company Communicator message is marked as "read"?

Thanks in advance.

Best regards,
Filippo Baroncini
Applied S.r.l.

![275872512-359fc027-1ef5-4697-a575-a91e84fb56d5](https://github.com/cristianoag/microsoft-teams-apps-company-communicator/assets/80096091/c61ec860-0ac2-471d-a061-152a0a24c496)

**Comment by luishdemetrio** [comment]
Hi @l3noir , it seems to be the same issue described here #57 :

https://github.com/cristianoag/microsoft-teams-apps-company-communicator/issues/57

It was already fixed. What is the version of CC that you are using?

**Comment by l3noir** [comment]
Thanks very much for the clarification! We still have the master 4.0 version.

We'll procede with an update.

Thanks again and best regards,
Filippo Baroncini

Applied S.r.l.
