### ISSUE TITLE
Company Communicator stop working when use New Teams version

### ISSUE THREAD

**Issue by CRVieiras** [cristianoag/microsoft-teams-apps-company-communicator#68]
My company turned on to use New version of Teams but I found that the communicator is error as attached, when I get back to normal Teams version "1.6.00.29964 (64-bit)" it worked fine.
please help to advise if we have version that able to use with new Teams please.

<img width="316" alt="282595898-a70728ca-9f65-48e3-b349-588b20ec0236" src="https://github.com/cristianoag/microsoft-teams-apps-company-communicator/assets/101516896/d731629b-1ff0-49c3-a026-2e33299c3a28">

**Comment by luishdemetrio** [comment]
That issue is happening for all CC versions due a change that was done on Azure FrontDoor. We provided a temporary fix today to direct call the APIs. Please rebuild (sync) the app service.

**Comment by Fadel1949** [comment]
Hello @cristianoag  , I have seen the official repo fix the problem. 
Has your repo fixed the same problem as the official repo? Thank you very much.
Ref. official repo https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1201#issuecomment-1824323987

**Comment by cristianoag** [comment]
Yes. You need to resync. Keep in mind that it is a temporary solution. It is basically a bypass of the front door for all calls to the api. As soon as front door gets fixed we will remove the bypass and you will need to resync again.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jackdawsonnv** [comment]
Hi @cristianoag , I am still experiencing the error message described above after syncing the app service and all three of the function services. Any suggestions to resolve it?

**Comment by cristianoag** [comment]
Please test using the teams client on the browser and clean the cache to make sure it is not influencing anything. If you have any firewalls between your clients and the app service, make sure you allow connections directly to the app service. What temporary fix does is bypass the front door for all API calls.

________________________________

**Comment by jackdawsonnv** [comment]
> Please test using the teams client on the browser and clean the cache to make sure it is not influencing anything. If you have any firewalls between your clients and the app service, make sure you allow connections directly to the app service. What temporary fix does is bypass the front door for all API calls.
> […](#)


Hi @cristianoag , Thank you for your quick reply. I already tried restarting the web app service and accessing it using the Teams client in a browser (after clearing the cache), but I am still seeing the same error. I have tried resyncing the app service twice now with the same results. Any other suggestions?

**Comment by cristianoag** [comment]
Do you have any firewalls between Teams clientes and app service? If yes, please check if the app service URL is on the whitelist.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jackdawsonnv** [comment]
> Do you have any firewalls between Teams clientes and app service? If yes, please check if the app service URL is on the whitelist. Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)
Yes, there is a firewall between the Teams client and the app service in the Azure cloud, but we do not restrict outbound access through our firewall AND this Company Communicator app was working perfectly until the new Teams client update. No other network or firewall changes have been made since this error message appeared. I have also tested this from a different location with the same error message.

**Comment by cristianoag** [comment]
Are you using master-v4.51? If yes, please resync it as I forgot to fix that version and just did it right now.
Cristiano
________________________________

**Comment by jackdawsonnv** [comment]
Actually, I am using the master branch. Should I be using another branch instead?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cristianoag** [comment]
master was already fixed. Sorry that was a change in front door that is impacting all instances of CC. The fix has worked for multiple customers so far. Need to troubleshoot as it looks like you have another problem.

Is the sync completing ok?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jackdawsonnv** [comment]
Yes. The sync is successful after which I restart the app service, cleared my browser cache, and then accessed the Teams client through the web browser but still get the same error message. I don’t want to do this if I don’t have to, but should I just delete and redeploy the entire app?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jackdawsonnv** [comment]
I was looking through the three Function apps and found new errors in the notification section that may be contributing to this problem. Please let me know if this could be the issue…
***@***.***


***@***.***
Jack Dawson​​​​
Director ‑ Information Technology​
 |
+1 (775) 412-4305<tel:+1%20(775)%20412-4305>

**Comment by cristianoag** [comment]
Functions weren’t affected by the issue and didn’t get any changes. So, if you’re seeing errors with functions those are being caused by another issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jackdawsonnv** [comment]
Ok, thanks. I only ask because these errors appeared after syncing.

***@***.***
Jack Dawson​​​​
Director ‑ Information Technology​
 |
+1 (775) 412-4305<tel:+1%20(775)%20412-4305>

**Comment by Fadel1949** [comment]
I have the same problem. After re-sync, I still encounter the same problem. Use branch master.

**Comment by MarkusMGB** [comment]
@cristianoag same here, deployed the fix still not working.

**Comment by CRVieiras** [comment]
@cristianoag , bom dia! Mesma situação aqui. Refiz o sync, porém o erro persiste

**Comment by cristianoag** [comment]
Ok here is the deal. I just tested and the latest master-v5.31 is working fine. Unfortunately, I don't have time neither the right environments to perform regression tests to previous versions, so I recommend everybody that still wants to use this community version to update to master-v5.31.

What do you need to do?

1. Check if you have key vault already deployed on your resource group. If you have it, then you just need to disconnect the App Service and all functions and point them to master-v5.31. You can do that by accessing deployment center for each on of those resources, clicking disconnect under Source and reconnect specifying the branch master-v5.31 instead of just master or any other version. Then click Sync and wait until all resources get synced without any errors. 
2. If you are in a previous version (if you don't have the key vault resource), then follow instructions available on the wiki and upgrade to the latest version.

Of course, you have the option to just wait until Front Door gets fixed and start passing the auth headers again to the back-end. Unfortunately, I don't have a date for when that is going to happen.

**Comment by Fadel1949** [comment]
@cristianoag  Hi Cristiano,
Regarding the master branch, do you have a plan for when the fix will be completed?
Thank you very much.

**Comment by cristianoag** [comment]
Master is based on v5.13 and this is just a temporary workaround for the front door problem. I don’t have an environment based on 5.13 to test and I don’t think the effort worth. You can upgrade to 5.31, move to the official version or just wait for the front door fix.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MarkusMGB** [comment]
@cristianoag We have the latest Build, we synched the CC with your temporary fix and still no luck new Teams App ist not working. We even have now some users with the same problem in Teams classic

**Comment by cristianoag** [comment]
I recommend you to use the official version. I’m sorry, no time to troubleshoot specific cases.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CeciliaRavera** [comment]
Hello. We have the same problem.. we redeployed to branch v5.31 and still not working :(

**Comment by cristianoag** [comment]
@CeciliaRavera and others. We just figured out that besides the update, you also need to temporarily disable the second rule in Front Door. After that restart the App Service and test. It will work.

![image](https://github.com/cristianoag/microsoft-teams-apps-company-communicator/assets/48498602/102372da-e3d8-4452-9cb5-876275e2be3a)

**Comment by PaoloCastAway** [comment]
@cristianoag, question. Not sure if I correctly understood the fix: is this fix/solution actually bypassing Front Door? I read somewhere else that the very first workaround was to bypass FD. My customer's policies do not allow such bypass, so I have to be sure to be compliant before start a new deployment

**Comment by cristianoag** [comment]
Yes, the temporary fix bypasses the Front Door. If your customer requires it, there is no solution until the Front Door service gets fixed.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Fadel1949** [comment]
@cristianoag 
I have a question: Why doesn't CC Branch Official have to disable the front door?

**Comment by CRVieiras** [comment]
Boa tarde!

Por gentileza, poderiam verificar essa questão? O Company Communicator funciona no "novo teams" no website, porém no app desktop continua apresentando erro.

Website Teams
![Captura de tela 2024-01-23 130335](https://github.com/cristianoag/microsoft-teams-apps-company-communicator/assets/101516896/3dff3565-640f-4f50-b9a0-23879b26444c)

Aplicativo Desktop Teams
![Captura de tela 2024-01-23 130606](https://github.com/cristianoag/microsoft-teams-apps-company-communicator/assets/101516896/2b790a88-586d-4fae-87f7-4f6f760d97b3)

**Comment by ostromecko** [comment]
Hi @cristianoag, I have done sync for the service app and all three functions, I'm pointing to master branch v5.31, I have also disabled the second rule for Azure front door but still I'm facing this issue. I'm checking both in the new desktop client and new browser client. How we can sort this issue out?

**Comment by ostromecko** [comment]
> Hi @cristianoag, I have done sync for the service app and all three functions, I'm pointing to master branch v5.31, I have also disabled the second rule for Azure front door but still I'm facing this issue. I'm checking both in the new desktop client and new browser client. How we can sort this issue out?

This issue on my end was resolved.

**Comment by CRVieiras** [comment]
> > Hi @cristianoag, I have done sync for the service app and all three functions, I'm pointing to master branch v5.31, I have also disabled the second rule for Azure front door but still I'm facing this issue. I'm checking both in the new desktop client and new browser client. How we can sort this issue out?
> 
> This issue on my end was resolved.

What did you do to solve the problem?

**Comment by Maxiz80** [comment]
> > > Hi @cristianoag, I have done sync for the service app and all three functions, I'm pointing to master branch v5.31, I have also disabled the second rule for Azure front door but still I'm facing this issue. I'm checking both in the new desktop client and new browser client. How we can sort this issue out?
> > 
> > 
> > This issue on my end was resolved.
> 
> What did you do to solve the problem?

Hi.
In my case cleaning the cache solved the problem afetr doing what you've already done

**Comment by ostromecko** [comment]
> > > Hi @cristianoag, I have done sync for the service app and all three functions, I'm pointing to master branch v5.31, I have also disabled the second rule for Azure front door but still I'm facing this issue. I'm checking both in the new desktop client and new browser client. How we can sort this issue out?
> > 
> > 
> > This issue on my end was resolved.
> 
> What did you do to solve the problem?

I have cleared cache few times in browser & desktop app and it finally worked.

**Comment by jvrabel88** [comment]
@cristianoag  I am still having issues, even after disabling the 2nd front door routing rule and clearing cache on browser/teams.  I have updated the app service and the 3 function apps to v5.31.  All of the function apps runtime version to ~4 and .NET version 6.  What else can I try or am I missing?

**Comment by cristianoag** [comment]
What is the error you’re receiving now?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jvrabel88** [comment]
"Sorry, an error occurred while trying to access this service."

**Comment by cristianoag** [comment]
Can you please make sure you are cleaning the cache of the browser and teams client? Got other customers with the error and cleaning the cache solved the issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jvrabel88** [comment]
Well it's been about a week since i made the change, i just checked teams on the web and it seems to be working in the new version, however the new teams version thick client is not working still.   Both the web and the thick client were not working earlier, so i'm assuming that the thick client will work eventually as well.  I'll keep monitoring. Thank you for the quick replies!

**Comment by cristianoag** [comment]
Please follow the instructions available in the following article to clean the teams client cache https://learn.microsoft.com/en-us/microsoftteams/troubleshoot/teams-administration/clear-teams-cache

It works on the client as well. It is just cache.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jvrabel88** [comment]
This worked, i must have been clearing the classic teams cache. I followed the instructions to reset the cache for new teams and it worked.  Thanks again!
